# docker-compose file
version: "3"

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/24

services:
  api:
    image: node:16.19.0
    container_name: twitter_api
    ports:
      - 3002:3002
    restart: always
    volumes:
      - ./backend:/app
    working_dir: /app
    command: >
      bash -c "npm ci &&
      npm run start:dev"
    networks:
      app_net:
        ipv4_address: 172.23.0.4

  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgres
    environment:
      - POSTGRES_ROOT_PASSWORD=root
      - POSTGRES_DB=twitter
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ="Asia/Tokyo"
    networks:
      app_net:
        ipv4_address: 172.23.0.3
