# docker-compose file
version: "3"

services:
  api:
    image: node:16.19.0
    container_name: twitter_api
    ports:
      - 3002:3002
    restart: always
    volumes:
      - ./backend:/app
    working_dir: /app
    command: >
      bash -c "npm ci &&
      npm run start:dev"

  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgres
    environment:
      - POSTGRES_ROOT_PASSWORD=root
      - POSTGRES_DB=twitter
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ="Asia/Tokyo"
